Normalize contractions
theochem/gbasis pull request #43
Opened 2019-04-11 05:11 UTC by kimt33

Working off of PR #42 

What:
1. Add `assign_norm_cont` to `ContractedCartesianGaussians`
2. Add attribute `norm_cont` for storing normalization constants for the contractions
3. Change name of property from `norm` to `norm_prim`
4. Make appropriate changes to tests and API

Since contraction coefficients are not always such that the contractions are normalized after normalizing the primitives, they need to be normalized. This means that they must access the `overlap` module, which introduces a bit of circular import. We can avoid circular import error by placing the import statement within a function, so the method `assign_norm_cont` to assign the attribute `norm_cont`. Normalization constants are stored to avoid recomputing it.

2019-04-11 05:13 UTC, kimt33 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add function for evaluating normalization constant for spherical Gaussian](https://trello.com/c/aq9rp2Ma/9-add-function-for-evaluating-normalization-constant-for-spherical-gaussian)

2019-04-11 05:16 UTC, kimt33 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add function for normalizing `ContractedCartesianGaussians`](https://trello.com/c/aIR0krb2/47-add-function-for-normalizing-contractedcartesiangaussians)

2019-04-11 19:03 UTC, wilhadams commented on tests/test_overlap.py
> +    """Test the norm of gbasis.eval.overlap_basis_spherical on the ANO-RCC basis set.
This one is STO-6G not ANO-RCC

2019-04-11 19:04 UTC, wilhadams commented on tests/test_overlap.py
> +    """Test the norm of gbasis.eval.overlap_basis_cartesian on the ANO-RCC basis set.
STO-6G not ANO-RCC

2019-04-11 20:38 UTC, kimt33 commented on tests/test_overlap.py
> +    """Test the norm of gbasis.eval.overlap_basis_spherical on the ANO-RCC basis set.
Thanks!

2019-04-14 20:24 UTC, wilhadams requested changes

2019-04-14 20:24 UTC, wilhadams commented on tests/test_overlap.py
> +    """Test the norm of gbasis.eval.overlap_basis_cartesian on the ANO-RCC basis set.
It still says ANO-RCC not STO-6G in the first line

2019-05-11 01:35 UTC, merged