Add functions for evaluating density related arrays
theochem/gbasis pull request #44
Opened 2019-04-11 20:33 UTC by kimt33

What
--------
1. Add function for evaluating density from basis set (list/tuple of `ContractedCartesianGaussians`)
2. Add function for evaluating arbitrary order derivative of density from basis set (list/tuple of `ContractedCartesianGaussians`)
3. Add function for evaluating the gradient of density
4. Clean up existing density code

Why
------
1. Since basis set is the data object used for most methods, this function will make it easier to utilize these functions (i.e. `evaluate_basis_spherical_lincomb` and `evaluate_deriv_basis_spherical_lincomb`)
2. Arbitrary order derivative will be used to get higher order derivative of the density (e.g. gradient, Laplacian, second-derivative tensor, etc)
3. Example of an application of the arbitrary order derivative
4. For consistent API

2019-04-11 20:34 UTC, kimt33 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add function for evaluating gradient of density](https://trello.com/c/cDN7pT4k/14-add-function-for-evaluating-gradient-of-density)

2019-04-11 20:34 UTC, kimt33 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add function for evaluating arbitrary order derivative of density](https://trello.com/c/OYLfDU07/15-add-function-for-evaluating-arbitrary-order-derivative-of-density)

2019-04-14 20:13 UTC, wilhadams requested changes

2019-04-14 20:13 UTC, wilhadams commented on gbasis/density.py
> +    """Return the density of given the transformed basis set at the given coordinates.
Remove "of"

2019-05-11 01:35 UTC, merged