WIP Add documentation
theochem/gbasis pull request #62
Opened 2019-06-02 22:10 UTC by kimt33

Documentation is currently a tex file (easier at the moment for compiling equations), but can be ported over to rst later.

Includes:
1. definitions
2. cartesian to spherical transformation
3. evaluations of contractions
4. evaluations of derivatives
5. evaluations of density matrix related properties
6. multipole moment integrals
7. overlap integrals
8. integrals over differential operators
9. integrals for interaction with point charges
10. electron-electron repulsion integral

Issues:
Does not cover the "how" aspect.
Errors in equations for stress tensors and ehrenfest forces

2019-06-02 22:14 UTC, kimt33 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add documentation for the ordering of the contractions](https://trello.com/c/KUFcbEQS/56-add-documentation-for-the-ordering-of-the-contractions)

2019-06-02 22:20 UTC, kimt33 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add documentation on conventions and features](https://trello.com/c/WZF8RNDu/66-add-documentation-on-conventions-and-features)

2019-06-03 15:47 UTC, kimt33 commented
Updated with the (hopefully) correct equations

2019-06-03 15:49 UTC, wilhadams requested changes

2019-06-03 15:49 UTC, wilhadams commented on docs/notes.tex
> +momentum, $\ell = a_x + a_y + a_z$, and the
remove "the"

2019-06-03 15:49 UTC, wilhadams commented on docs/notes.tex
> +Therefore, we will denote Cartesian primitives as primitives.
"primitives" will refer to Cartesian primitives

2019-06-03 15:49 UTC, wilhadams commented on docs/notes.tex
> +\subsection{Transformation of Spherical to Cartesian}
Spherical primitives to Cartesian primitives

2019-06-03 15:49 UTC, wilhadams commented on docs/notes.tex
> +\section{Contraction}
Contractions (plural)

2019-06-03 15:49 UTC, wilhadams commented on docs/notes.tex
> +Generalized contractions is a set of contractions that have the same center
are a set

2019-06-03 15:49 UTC, wilhadams commented on docs/notes.tex
> +In \verb|gbasis|, contractions can be derivatized to orbitrary orders.
arbitrary

2019-06-03 19:18 UTC, merged